#include "ros/ros.h"
#include "std_msgs/String.h"

// This tutorial demonstrates a simple receipt of messages over the ROS system.
// We'll subscribe it to the topic generated by the talker.cpp publisher.

void chatterCallback(const std_msgs::String::ConstPtr& msg)
{
  ROS_INFO("[Listener] I heard: %s", msg->data.c_str());
}

// ------------------------------------------

int main(int argc, char **argv)
{
  // initialize ROS. Third argument is the name of the node
  ros::init(argc, argv, "listener");

  // node handle
  ros::NodeHandle n;

  //Let ROS know this node wants to receive information on a given topic.
  ros::Subscriber sub = n.subscribe("chatter", 1000, chatterCallback);

  // enter a loop pumping callbacks (I assume making requests to get the messages)
  ros::spin();
  
  return 0;
}
